[package]
name = "backend_api"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = { workspace = true }

[dependencies]
backend_logging = { path = "../../backend_logging" }
backend_paths = { path = "../../backend_paths" }
database_types = { path = "../../database_types" }
sepa_types = { path = "../../sepa_types" }
config = { workspace = true }
flexi_logger = { workspace = true }
flutter_rust_bridge = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[features]
default = []
mysql = []
postgres = []
