name: Install backend dependencies
runs:
  using: "composite"
  steps:
    - name: Install Rust command line tools
      run: |
        cargo install diesel_cli --no-default-features --features "postgres"
        cargo install diesel_cli_ext