[workspace]
resolver = "3"
members = [
    "backend_logging",
    "backend_macros",
    "backend_paths",
    "backend_testing",
    "database_types",
    "interface/backend_api",
    "interface/database_api",
    "interface/sepa_api",
    "sepa_types",
    "sepa_xsd_to_rust_generator",
]

[workspace.dependencies]
chrono = { version = "^0.4.42", features = ["alloc", "unstable-locales"] }
clap = { version = "^4.5.53", features = ["derive"] }
config = "^0.15.19"
diesel = { version = "^2.2.6", features = ["chrono"] }
directories = "^6.0.0"
dotenvy = "^0.15.7"
flexi_logger = { version = "^0.31.10", features = [
    "async",
    "colors",
    "specfile",
] }
flutter_rust_bridge = { version = "=2.12.0", features = ["chrono"] }
flutter_rust_bridge_codegen = "=2.12.0"
log = "^0.4.25"
proc-macro2 = "^1.0.86"
quote = "^1.0.37"
russh = "^0.62.6"
sea-query = "^1.0.1"
serde = { version = "^1.0.228", features = ["derive"] }
serde_json = "^1.0.150"
speculoos = "^0.13.0"
sqlx = { version = "^0.9.0", features = ["runtime-tokio", "any"] }
syn = "^3.0.3"
tokio = "^1.52.1"
toml = "^1.1.4"
xsd-parser = "^1.5.2"
xsd-parser-types = { version = "^0.2.1", features = ["quick-xml"] }
