[package]
name = "backend"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "backend"
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.78.0"

[dependencies]
flutter_rust_bridge = "1.78.0"
rand = "0.8.4"