name: Install frontend dependencies
description: Install all dependencies required for building the frontend
runs:
  using: "composite"
  steps:
    # WARN It is required to prepare building backend before
    - name: Install Linux packages
      run: |
        sudo apt install libgtk-3-0 libgtk-3-dev
      shell: bash
    - name: Install Ninja
      uses: turtlesec-no/get-ninja@1.1.0
    - name: Install Flutter packages
      working-directory: ${{ github.workspace }}/frontend
      run: flutter pub get
      shell: bash