name: Setup PostgreSQL
description: Set up and start a PostgreSQL server based on the environment variables given in the repository
runs:
  using: "composite"
  steps:
    # WARN It is required to call TrackerSB/Green3Neo-Prepare-Action@main before
    # WARN It is required to install "just" before
    - name: Setup PostgreSQL server
      uses: Daniel-Marynicz/postgresql-action@master
      with:
        postgres_db:  ${{ env.DB_NAME }}
        postgres_user: ${{ env.DB_USER }}
        postgres_password: ${{ env.DB_PASSWORD }}
    - name: Create demo DB tables
      run: just database-create-tables
      shell: bash