name: Setup PostgreSQL
description: Set up and start a PostgreSQL server based on the environment variables given in the repository
runs:
  using: "composite"
  steps:
    - name: Install just command runner
      uses: extractions/setup-just@v2
    - name: Setup PostgreSQL server
      uses: Daniel-Marynicz/postgresql-action@master
      with:
        postgres_db:  ${{ env.BUILD_DB_NAME }}
        postgres_user: ${{ env.BUILD_DB_USER }}
        postgres_password: ${{ env.BUILD_DB_PASSWORD }}
    - name: Create empty DB tables
      run: just database-create-tables
      shell: bash