name: Setup PostgreSQL
runs:
  using: "composite"
  steps:
    # WARN It is required to call TrackerSB/Green3Neo-Prepare-Action@main before this action
    - name: Setup PostgreSQL server
      uses: Daniel-Marynicz/postgresql-action@master
      with:
        postgres_db:  ${{ env.DB_NAME }}
        postgres_user: ${{ env.DB_USER }}
        postgres_password: ${{ env.DB_PASSWORD }}