name: Install backend dependencies
description: Install all dependencies required for building the backend
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-db
    - name: Install FVM
      run: curl -fsSL https://fvm.app/install.sh | bash
      shell: bash
    - name: Install flutter via FVM
      working-directory: ${{ github.workspace }}/frontend
      run: fvm install
      shell: bash
    - name: Install Flutter packages
      working-directory: ${{ github.workspace }}/frontend
      run: fvm flutter pub get
      shell: bash
    - name: Install Rust command line tools for building
      run: |
        if [ "${{ env.BUILD_DB_PROTOCOL }}" = "postgres" ]; then
          cargo install diesel_cli --no-default-features --features "postgres"
        elif [ "${{ env.BUILD_DB_PROTOCOL }}" = "mysql" ]; then
          cargo install diesel_cli --no-default-features --features "mysql"
        else
          echo "Unsupported DB backend ${{ env.BUILD_DB_PROTOCOL }}"
          exit 1
        fi
        cargo install diesel_cli_ext
        cargo install flutter_rust_bridge_codegen@2.12.0
      shell: bash
