name: Install backend dependencies
description: Install all dependencies required for building the backend
inputs:
  db-backend:
    description: "Choose DB backend (Either PostgreSQL or MySQL)"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-postgre
      if: inputs.db-backend == 'PostgreSQL'
    - uses: ./.github/actions/setup-mysql
      if: inputs.db-backend == 'MySQL'
    - name: Fail if unsupported SQL DB
      if: inputs.db-backend != 'PostgreSQL' && inputs.db-backend != 'MySQL'
      run: exit 1
      shell: bash
    - name: Install Flutter SDK
      uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable
        version: latest
    - name: Install Rust command line tools for building
      run: |
        cargo install diesel_cli --no-default-features --features "postgres"
        cargo install diesel_cli_ext
        cargo install flutter_rust_bridge_codegen@2.11.1
      shell: bash