name: Install backend dependencies
description: Install all dependencies required for building the backend
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-postgre
      if: env.BUILD_DB_PROTOCOL == 'postgres'
    - uses: ./.github/actions/setup-mysql
      if: env.BUILD_DB_PROTOCOL == 'mysql'
    - name: Fail if unsupported SQL DB
      if: env.BUILD_DB_PROTOCOL != 'postgres' && env.BUILD_DB_PROTOCOL != 'mysql'
      run: exit 1
      shell: bash
    - name: Install Flutter SDK
      uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable
        version: latest
    - name: Install Rust command line tools for building
      run: |
        if [ "${{ env.BUILD_DB_PROTOCOL }}" = "postgres" ]; then
          cargo install diesel_cli --no-default-features --features "postgres"
        elif [ "${{ env.BUILD_DB_PROTOCOL }}" = "mysql" ]; then
          cargo install diesel_cli --no-default-features --features "mysql"
        else
          echo "Unsupported DB backend ${{ env.BUILD_DB_PROTOCOL }}"
          exit 1
        fi
        cargo install diesel_cli_ext
        cargo install flutter_rust_bridge_codegen@2.11.1
      shell: bash
