name: Install backend dependencies
description: Install all dependencies required for building the backend
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-postgre
    - name: Install Flutter SDK
      uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable
        version: latest
    - name: Install Rust command line tools for building
      run: |
        cargo install diesel_cli --no-default-features --features "postgres"
        cargo install diesel_cli_ext
        cargo install flutter_rust_bridge_codegen@2.11.1
      shell: bash