name: green3neo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.0.0-dev.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  ffigen: ^9.0.0
  provider: ^6.1.1

flutter:
  uses-material-design: true
