name: Install frontend dependencies
runs:
  using: "composite"
  steps:
    - name: Install Linux packages
      run: |
        sudo apt install libgtk-3-0 libgtk-3-dev
    - name: Install Ninja
      uses: turtlesec-no/get-ninja@1.1.0
    - name: Install Rust command line tools
      run: |
        cargo install flutter_rust_bridge_codegen@2.4.0
    - name: Install Flutter SDK
      uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable
        version: latest
    - name: Install Flutter packages
      working-directory: ${{ github.workspace }}/frontend
      run: flutter pub get