[package]
name = "database_api"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "=2.12.0"

[dev-dependencies]
backend_testing = { path = "../../backend_testing" }
speculoos = "0.13.0"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "any"] }

[dependencies]
backend_logging = { path = "../../backend_logging" }
backend_macros = { path = "../../backend_macros" }
database_types = { path = "../../database_types" }
chrono = "0.4.31"
diesel = { version = "2.2.6", features = ["chrono"] }
flexi_logger = { version = "0.31.10", features = [
    "async",
    "colors",
    "specfile",
] }
flutter_rust_bridge = { version = "=2.12.0", features = ["chrono"] }
log = "0.4.25"
russh = "0.62.6"
sea-query = "1.0.1"
serde = "1.0.220"
serde_json = "1.0.150"
tokio = "1.52.1"

[features]
default = []
mysql = ["diesel/mysql", "sqlx/mysql", "database_types/mysql"]
postgres = ["diesel/postgres", "sqlx/postgres", "database_types/postgres"]
