name: Setup MySQL
description: Set up and start a MySQL server based on the environment variables given in the repository
runs:
  using: "composite"
  steps:
    - name: Install just command runner
      uses: extractions/setup-just@v3.1.0
    - name: Setup MySQL server
      id: setup-mariadb
      uses: shogo82148/actions-setup-mysql@v1.52.1
      with:
        distribution: "mariadb"
        mysql-version: "12.3"
        my-cnf: |
          bind-address=0.0.0.0
          port=${{ env.BUILD_DB_PORT }}
        user: ${{ env.BUILD_DB_USER }}
        password: ${{ env.BUILD_DB_PASSWORD }}
    - name: Create DB
      run: |
        mariadb \
          -h ${{ env.BUILD_DB_HOST }} \
          -P ${{ env.BUILD_DB_PORT }} \
          -u ${{ env.BUILD_DB_USER }} \
          -p"${{ env.BUILD_DB_PASSWORD }}" \
          -e "CREATE OR REPLACE DATABASE ${{ env.BUILD_DB_NAME }};"
      shell: bash
    - name: Grant CREATE privilege for sqlx test databases
      run: |
        mariadb \
          -h ${{ env.BUILD_DB_HOST }} \
          -P ${{ env.BUILD_DB_PORT }} \
          -u root \
          -e "GRANT ALL PRIVILEGES ON \`_sqlx_test_%\`.* TO '${{ env.BUILD_DB_USER }}'@'%';" \
          -e "GRANT CREATE ON *.* TO '${{ env.BUILD_DB_USER }}'@'%';" \
          -e "FLUSH PRIVILEGES;"
      shell: bash
    - name: Create empty DB tables
      run: just database-create-tables
      shell: bash
