name: Build project
on: [push]
jobs:
  Build-All:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: myFancyDatabaseName
          POSTGRES_PASSWORD: prettySafePassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install just command runner
        uses: extractions/setup-just@v2
      - name: Install diesel_cli
        run: cargo install diesel_cli --no-default-features --features "postgres"
      - name: Install diesel_cli_ext
        run: cargo install diesel_cli_ext
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Load environment variables
        uses: falti/dotenv-action@v1.1.2
        with:
          path: ${{ github.workspace }}/green3neo/.env
          log-variables: true
      # - name: Setup PostgreSQL server
      #   uses: harmon758/postgresql-action@v1
      #   with:
      #     postgresql db: ${{ steps.dotenv.outputs.db_name }}
      #     postgresql user: ${{ steps.dotenv.outputs.db_user }}
      #     postgresql password: ${{ steps.dotenv.outputs.db_password }}
      - working-directory: ${{ github.workspace }}/green3neo
        run: just build
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
