name: Build project
on:
  pull_request:
    branches:
      - main
jobs:
  Build-All:
    runs-on: ubuntu-latest
    steps:
      - uses: TrackerSB/Green3Neo-Prepare-Action@main
      - name: Install just command runner
        uses: extractions/setup-just@v2
      - uses: ./.github/actions/install-frontend-dependencies
      - uses: ./.github/actions/install-backend-dependencies
      - name: Setup PostgreSQL server
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_db:  ${{ env.DB_NAME }}
          postgres_user: ${{ env.DB_USER }}
          postgres_password: ${{ env.DB_PASSWORD }}
      - name: Create DB tables
        run: just database-create-tables
      - name: Execute full build
        run: just build
