name: Build project
on:
  pull_request:
    branches:
      - main
jobs:
  Build-All:
    runs-on: ubuntu-latest
    steps:
      - uses: TrackerSB/Green3Neo-Prepare-Action@main
      - uses: ./.github/actions/install-frontend-dependencies
      - uses: ./.github/actions/install-backend-dependencies
      - name: Install just command runner
        uses: extractions/setup-just@v2
      - uses: ./.github/actions/setup-postgre
      - name: Execute full build
        run: just build
