name: Build project
on: [push]
jobs:
  Build-All:
    runs-on: ubuntu-latest
    steps:
      - name: Install just command runner
        uses: extractions/setup-just@v2
      - name: Install diesel
        run: cargo install diesel
      - name: Install diesel_cli_ext
        run: cargo install diesel_cli_ext
      - name: Clone repository
        uses: actions/checkout@v4
      - working-directory: ${{ github.workspace }}/green3neo
        run: just build
