name: Build project
on: [push]
jobs:
  Build-All:
    runs-on: ubuntu-latest
    steps:
      - name: Install just command runner
        uses: extractions/setup-just@v2
      - working-directory: ./green3neo
        run: just build
