on:
  workflow_call:
jobs:
  prepare-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Load environment variables
        uses: xom9ikk/dotenv@v2.3.0