name: Prepare repository
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
jobs:
  prepare-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{inputs.ref}}
      - name: Load environment variables
        uses: xom9ikk/dotenv@v2.3.0