name: Test project
on:
  pull_request:
    branches:
      - main
jobs:
  Test-All:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        db-protocol: ['postgres', 'mysql']
    steps:
      - uses: TrackerSB/Green3Neo-Prepare-Action@main
      - name: Override environment variables and update dependent ones
        run: |
          echo "BUILD_DB_PROTOCOL=${{ matrix.db-protocol }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ matrix.db-protocol }}://$BUILD_DB_USER:$BUILD_DB_PASSWORD@$BUILD_DB_HOST:$BUILD_DB_PORT/$BUILD_DB_NAME" >> $GITHUB_ENV
        shell: bash
      - uses: ./.github/actions/prepare-application-build
      - name: Install command line for executing tests and combining results
        run: |
          cargo install --locked cargo-nextest
          dart pub global activate junitreport
        shell: bash
      - name: Execute tests
        run: just test
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            backend/target/nextest/default/junit.xml
            frontend/build/junit.xml
          comment_mode: off
          check_run: true
          ignore_runs: true
          job_summary: true
