// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::Queryable;
use diesel::Selectable;
use diesel::Identifiable;
use backend_macros::make_fields_non_final;
use flutter_rust_bridge::frb;
use crate::schema::*;

#[derive(Queryable,Selectable, Identifiable)]
#[diesel(primary_key(membershipid))]
#[diesel(table_name = member)]
#[make_fields_non_final]
pub struct Member {
    pub membershipid: i32,
    pub prename: String,
    pub surname: String,
    pub title: Option<String>,
    pub ismale: bool,
    pub street: String,
    pub housenumber: String,
    pub zipcode: String,
    pub city: String,
    pub isactive: bool,
    pub isfoundingmember: bool,
    pub ishonorarymember: bool,
    pub iscontributionfree: bool,
    pub contributorsinceyear: Option<i32>,
    pub phonenumber: Option<String>,
    pub mobilenumber: Option<String>,
    pub email: Option<String>,
    pub accountholderprename: Option<String>,
    pub accountholdersurname: Option<String>,
    pub iban: String,
    pub bic: String,
    pub honoraryyears: Option<Vec<Option<i32>>>,
    pub contributionhonoraryyears: Option<Vec<Option<i32>>>,
    pub hasgauehrenzeichen: bool,
    pub isehrenschriftf_hrer: bool,
    pub isehrenvorstand: bool,
    pub ismemberofboard: bool,
}

